/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GuestProfile {
  'id' : string,
  'paymentStatus' : PaymentStatus,
  'createdAt' : Time,
  'rentAmount' : bigint,
  'fullName' : string,
  'roomNumber' : string,
  'billDueDate' : string,
  'phoneNumber' : string,
}
export interface Notification {
  'id' : string,
  'status' : NotificationStatus,
  'billingMonth' : bigint,
  'createdAt' : Time,
  'dueDate' : string,
  'guestName' : string,
  'roomNumber' : string,
  'message' : string,
  'cleared' : boolean,
  'amount' : bigint,
  'billingYear' : bigint,
  'guestId' : string,
}
export type NotificationStatus = { 'active' : null } |
  { 'cleared' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGuest' : ActorMethod<
    [string, string, string, string, bigint, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeOwnerPin' : ActorMethod<[string], undefined>,
  'clearNotification' : ActorMethod<[string], undefined>,
  'createNotification' : ActorMethod<[string, string], undefined>,
  'generateMonthlyBillsTrigger' : ActorMethod<[bigint, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGuests' : ActorMethod<[], Array<GuestProfile>>,
  'getMonthlyBillNotifications' : ActorMethod<
    [bigint, bigint],
    Array<Notification>
  >,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getNotificationsForGuest' : ActorMethod<[string], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsCleared' : ActorMethod<[string], undefined>,
  'removeGuest' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGuest' : ActorMethod<
    [string, string, string, string, bigint, string, PaymentStatus],
    undefined
  >,
  'validateOwnerPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];