/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Time = IDL.Int;
export const GuestProfile = IDL.Record({
  'id' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'createdAt' : Time,
  'rentAmount' : IDL.Nat,
  'fullName' : IDL.Text,
  'roomNumber' : IDL.Text,
  'billDueDate' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const NotificationStatus = IDL.Variant({
  'active' : IDL.Null,
  'cleared' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'status' : NotificationStatus,
  'billingMonth' : IDL.Nat,
  'createdAt' : Time,
  'dueDate' : IDL.Text,
  'guestName' : IDL.Text,
  'roomNumber' : IDL.Text,
  'message' : IDL.Text,
  'cleared' : IDL.Bool,
  'amount' : IDL.Nat,
  'billingYear' : IDL.Nat,
  'guestId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGuest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeOwnerPin' : IDL.Func([IDL.Text], [], []),
  'clearNotification' : IDL.Func([IDL.Text], [], []),
  'createNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'generateMonthlyBillsTrigger' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGuests' : IDL.Func([], [IDL.Vec(GuestProfile)], ['query']),
  'getMonthlyBillNotifications' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getNotificationsForGuest' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsCleared' : IDL.Func([IDL.Text], [], []),
  'removeGuest' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGuest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        PaymentStatus,
      ],
      [],
      [],
    ),
  'validateOwnerPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Time = IDL.Int;
  const GuestProfile = IDL.Record({
    'id' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'createdAt' : Time,
    'rentAmount' : IDL.Nat,
    'fullName' : IDL.Text,
    'roomNumber' : IDL.Text,
    'billDueDate' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const NotificationStatus = IDL.Variant({
    'active' : IDL.Null,
    'cleared' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'status' : NotificationStatus,
    'billingMonth' : IDL.Nat,
    'createdAt' : Time,
    'dueDate' : IDL.Text,
    'guestName' : IDL.Text,
    'roomNumber' : IDL.Text,
    'message' : IDL.Text,
    'cleared' : IDL.Bool,
    'amount' : IDL.Nat,
    'billingYear' : IDL.Nat,
    'guestId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGuest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeOwnerPin' : IDL.Func([IDL.Text], [], []),
    'clearNotification' : IDL.Func([IDL.Text], [], []),
    'createNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'generateMonthlyBillsTrigger' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGuests' : IDL.Func([], [IDL.Vec(GuestProfile)], ['query']),
    'getMonthlyBillNotifications' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getNotificationsForGuest' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsCleared' : IDL.Func([IDL.Text], [], []),
    'removeGuest' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGuest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          PaymentStatus,
        ],
        [],
        [],
      ),
    'validateOwnerPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };